# Generated by Django 4.0 on 2021-12-26 17:52

from django.db import migrations

# this migration just change the name of the one field in the product model
class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='price',
        ),
    ]
