# Generated by Django 4.0 on 2021-12-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211227_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_atus',
            new_name='payment_status',
        ),
    ]
